exports.config = {
  runner: 'local',
  specs: ['./automation/e2e/specs/mobile.bakery.appium.e2e.js'],
  maxInstances: 1,
  hostname: '127.0.0.1',
  port: 4723,
  path: '/',
  capabilities: [
    {
      platformName: 'Android',
      'appium:automationName': 'UiAutomator2',
      'appium:deviceName': 'Android Emulator',
      'appium:platformVersion': '13',
      'appium:browserName': 'Chrome',
      'appium:chromedriverAutodownload': true,
      'appium:noReset': true,
      'appium:skipDeviceInitialization': true,
      'appium:ignoreHiddenApiPolicyError': true,
      'appium:adbExecTimeout': 300000,
      'appium:uiautomator2ServerInstallTimeout': 300000,
      'appium:uiautomator2ServerLaunchTimeout': 300000,
      'appium:newCommandTimeout': 240,
    },
  ],
  logLevel: 'info',
  bail: 0,
  baseUrl: 'http://10.0.2.2:5173',
  waitforTimeout: 15000,
  connectionRetryTimeout: 900000,
  connectionRetryCount: 4,
  framework: 'mocha',
  reporters: ['spec'],
  services: [],
  mochaOpts: {
    ui: 'bdd',
    timeout: 180000,
  },
}
